name: car_iot_ble
description: car-iot BLE dashboard
publish_to: none
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  flutter_appauth: ^12.0.2
  flutter_blue_plus: ^1.32.0
  flutter_secure_storage: ^10.3.1
  geolocator: ^14.0.3
  http: ^1.6.0
  percent_indicator: ^4.2.5
  permission_handler: ^11.3.0
  shared_preferences: ^2.5.5
  wakelock_plus: ^1.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
